title:               Lagrange
tagline:             a minimalist Jekyll theme
email:               your-email@domain.com
description:
baseurl:             "/Lagrange" # the subpath of your site, e.g. /blog
url:                 "https://lenpaul.github.io" # the base hostname & protocol for your site
twitter_username:    jekyllrb
github_username:     jekyll

# Build settings
markdown:            kramdown
