title:               Lagrange
tagline:             a minimalist Jekyll theme
description:
baseurl:             #"/Lagrange"
url:                 #"https://lenpaul.github.io"
author:
  name:              "Paul Le"
  email:             "l.nguyen.paul@gmail.com"
  twitter:           "paululele"
  instagram:         "paululele"
  github:            "lenpaul"
  facebook:          "Le.Paul.94"
  linkedin:          "lenpaul"

gems:                [jekyll-paginate]
paginate:            5


# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
