title:               Lagrange
tagline:             a minimalist Jekyll theme
email:               your-email@domain.com
description:
baseurl:             "/Lagrange"
url:                 "https://lenpaul.github.io"
author:
  name:              "Paul Le"
  email:             "l.nguyen.paul@gmail.com"
  twitter:           "paululele"
  instagram:         "paululele"
  github:            "lenpaul"
  facebook:          "Le.Paul.94"

# Build settings
markdown:            kramdown
